### ISSUE TITLE
询问guozhi nav

### ISSUE THREAD

**Issue by hiing** [guozhivip/guozhivip.github.io#38]
因为实在感叹于您做的果汁导航，以及打开速度。由于自己并不懂css自己网页设计…
请问是否可给予果汁导航的源码？ 我会遵循以下:
1.只在自己的主站上用（hiing.net /之前一直用的是Livid的startpage）
2.只添加自己的链接，不会使用您目前在导航上的链接
3.我会在醒目位置，页脚？处标注好源码来自于您。
4.如果有4的话，请您联系我   ldcr99#gmail
万分
谢谢

**Comment by guozhivip** [comment]
感谢您的肯定，为防止他人恶意盗取源码并公开售卖等用于商业用途，目前果汁导航暂未有开源打算，望理解。
